deployment:
  # image: tidepool/tide-whisperer:master-latest
  image: docker.ci.diabeloop.eu/tide-whisperer
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
