version: '3.4'

services:
  mongo:
    image: docker.ci.diabeloop.eu/mongo-yourloops:3.6
    volumes:
      - ${MONGO_VOLUME}:/data/db
    ports:
     - '27017:27017'
#    command: mongod --auth --config /etc/mongod.conf
    command: mongod  --config /etc/mongod/mongo.conf

  blip:
    image: docker.ci.diabeloop.eu/blip
    depends_on:
      - hakken
    # build: ${BLIP_DIR}
    # volumes:
    #   - ${BLIP_DIR}:/app:cached
    #   - /app/node_modules
    #   - /app/dist
    #   - ${PLATFORM_CLIENT_DIR}:/tidepool-platform-client:cached
    #   - /tidepool-platform-client/node_modules
    #   - ${TIDELINE_DIR}:/tideline:cached
    #   - /tideline/node_modules
    #   - ${VIZ_DIR}:/@tidepool/viz:cached
    #   - viz-dist:/@tidepool/viz/dist:ro
    ports:
      - '3000:3000'
    environment:
      - API_HOST=${BLIP_API_HOST}
      - DEV_TOOLS
      - DISCOVERY_HOST
      - NODE_ENV
      - PORT=${BLIP_PORT}
      - PUBLISH_HOST
      - WEBPACK_DEVTOOL

  gatekeeper:
    image: docker.ci.diabeloop.eu/gatekeeper
    depends_on:
      - hakken
    # build: ${GATEKEEPER_DIR}
    # volumes:
    #   - ${GATEKEEPER_DIR}:/app:cached
    #   - /app/node_modules
    ports:
      - '${GATEKEEPER_PORT_PREFIX}9123:${GATEKEEPER_PORT_PREFIX}9123'
    environment:
      - DISCOVERY_HOST
      - GATEKEEPER_SECRET
      - MONGO_CONNECTION_STRING=${GATEKEEPER_MONGO_CONNECTION_STRING}
      - NODE_ENV
      - PORT=${GATEKEEPER_PORT}
      - PUBLISH_HOST
      - SERVER_SECRET
      - SERVICE_NAME="${GATEKEEPER_SERVICE_NAME}"
      - USER_API_SERVICE

  hakken:
    image: docker.ci.diabeloop.eu/hakken
    # build: ${HAKKEN_DIR}
    # volumes:
    #   - ${HAKKEN_DIR}:/app:cached
    #   - /app/node_modules
    ports:
      - '${HAKKEN_PORT_PREFIX}8000:${HAKKEN_PORT_PREFIX}8000'
    environment:
      - ANNOUNCE_HOST
      - DISCOVERY_HEARTBEAT_INTERVAL
      - DISCOVERY_HOST
      - LOG_HEARTBEATS
      - NODE_ENV
      - PORT=${HAKKEN_PORT}

  highwater:
    image: docker.ci.diabeloop.eu/highwater
    depends_on:
      - hakken
    # build: ${HIGHWATER_DIR}
    # volumes:
    #   - ${HIGHWATER_DIR}:/app:cached
    #   - /app/node_modules
    ports:
      - '${HIGHWATER_PORT_PREFIX}9191:${HIGHWATER_PORT_PREFIX}9191'
    environment:
      - DISCOVERY_HOST
      - METRICS_APIKEY
      - METRICS_UCSF_APIKEY
      - NODE_ENV
      - PORT=${HIGHWATER_PORT}
      - PUBLISH_HOST
      - SALT_DEPLOY="${HIGHWATER_SALT}"
      - SERVER_SECRET
      - SERVICE_NAME="${HIGHWATER_SERVICE_NAME}"
      - USER_API_SERVICE

  hydrophone:
    image: docker.ci.diabeloop.eu/hydrophone
    depends_on:
      - hakken
    # build:
    #   context: ${HYDROPHONE_DIR}
    #   target: ${HYDROPHONE_BUILD_TARGET}
    # volumes:
    #   - ${HYDROPHONE_DIR}:/go/src/github.com/tidepool-org/hydrophone:cached
    #   - /go/src/github.com/tidepool-org/hydrophone/dist
    ports:
      - '${HYDROPHONE_PORT_PREFIX}9157:${HYDROPHONE_PORT_PREFIX}9157'
    environment:
      - TIDEPOOL_HYDROPHONE_ENV
      - TIDEPOOL_HYDROPHONE_SERVICE

  jellyfish:
    image: docker.ci.diabeloop.eu/jellyfish
    depends_on:
      - hakken
    # build: ${JELLYFISH_DIR}
    # volumes:
    #   - ${JELLYFISH_DIR}:/app:cached
    #   - /app/node_modules
    ports:
      - '${JELLYFISH_PORT_PREFIX}9122:${JELLYFISH_PORT_PREFIX}9122'
    environment:
      - DISCOVERY_HOST
      - GATEKEEPER_SERVICE
      - MINIMUM_UPLOADER_VERSION
      - MONGO_CONNECTION_STRING=${JELLYFISH_MONGO_CONNECTION_STRING}
      - NODE_ENV
      - PORT=${JELLYFISH_PORT}
      - PUBLISH_HOST
      - SALT_DEPLOY="${JELLYFISH_SALT}"
      - SCHEMA_VERSION
      - SEAGULL_SERVICE
      - SERVER_SECRET
      - SERVE_STATIC
      - SERVICE_NAME="${JELLYFISH_SERVICE_NAME}"
      - USER_API_SERVICE

  message-api:
    image: docker.ci.diabeloop.eu/message-api
    depends_on:
      - hakken
    # build: ${MESSAGE_API_DIR}
    # volumes:
    #   - ${MESSAGE_API_DIR}:/app:cached
    #   - /app/node_modules
    ports:
      - '${MESSAGE_API_PORT_PREFIX}9119:${MESSAGE_API_PORT_PREFIX}9119'
    environment:
      - DISCOVERY_HOST
      - GATEKEEPER_SERVICE
      - METRICS_SERVICE
      - MONGO_CONNECTION_STRING=${MESSAGE_API_MONGO_CONNECTION_STRING}
      - NODE_ENV
      - PORT=${MESSAGE_API_PORT}
      - PUBLISH_HOST
      - SEAGULL_SERVICE
      - SERVER_NAME
      - SERVER_SECRET
      - SERVICE_NAME="${MESSAGE_API_SERVICE_NAME}"
      - USER_API_SERVICE

  platform-auth:
    image: docker.ci.diabeloop.eu/platform-auth
    # build:
    #   context: ${PLATFORM_AUTH_DIR}
    #   dockerfile: Dockerfile.auth
    #   target: ${PLATFORM_AUTH_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_AUTH_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    ports:
      - '${PLATFORM_AUTH_PORT_PREFIX}9222:${PLATFORM_AUTH_PORT_PREFIX}9222'
    environment: &platform-environment
      - TIDEPOOL_ENV
      - TIDEPOOL_LOGGER_LEVEL
      - TIDEPOOL_STORE_ADDRESSES
      - TIDEPOOL_STORE_DATABASE
      - TIDEPOOL_STORE_USERNAME
      - TIDEPOOL_STORE_PASSWORD
      - TIDEPOOL_STORE_SOURCE
      ##
      - TIDEPOOL_AUTH_STORE_USERNAME
      - TIDEPOOL_AUTH_STORE_PASSWORD
      - TIDEPOOL_AUTH_STORE_SOURCE

      - TIDEPOOL_PROFILE_STORE_USERNAME
      - TIDEPOOL_PROFILE_STORE_PASSWORD
      - TIDEPOOL_PROFILE_STORE_SOURCE

      - TIDEPOOL_MESSAGE_STORE_USERNAME
      - TIDEPOOL_MESSAGE_STORE_PASSWORD
      - TIDEPOOL_MESSAGE_STORE_SOURCE

      - TIDEPOOL_PERMISSION_STORE_USERNAME
      - TIDEPOOL_PERMISSION_STORE_PASSWORD
      - TIDEPOOL_PERMISSION_STORE_SOURCE

      - TIDEPOOL_SESSION_STORE_USERNAME
      - TIDEPOOL_SESSION_STORE_PASSWORD
      - TIDEPOOL_SESSION_STORE_SOURCE

      - TIDEPOOL_BLOB_CLIENT_ADDRESS
      - TIDEPOOL_BLOB_SERVICE_SERVER_ADDRESS
      - TIDEPOOL_BLOB_SERVICE_UNSTRUCTURED_STORE_TYPE
      - TIDEPOOL_BLOB_SERVICE_UNSTRUCTURED_STORE_FILE_DIRECTORY
      - TIDEPOOL_BLOB_SERVICE_UNSTRUCTURED_STORE_S3_BUCKET
      - TIDEPOOL_BLOB_SERVICE_UNSTRUCTURED_STORE_S3_PREFIX
      - TIDEPOOL_BLOB_SERVICE_SECRET


      - TIDEPOOL_CONFIRMATION_STORE_USERNAME
      - TIDEPOOL_CONFIRMATION_STORE_PASSWORD
      - TIDEPOOL_CONFIRMATION_STORE_SOURCE

      # DEPRECATED_DATA_STORE
      - TIDEPOOL_DEPRECATED_DATA_STORE_STORE_USERNAME
      - TIDEPOOL_DEPRECATED_DATA_STORE_STORE_PASSWORD
      - TIDEPOOL_DEPRECATED_DATA_STORE_STORE_SOURCE

      - TIDEPOOL_STORE_TLS
      - TIDEPOOL_STORE_MECHANISM
      - TIDEPOOL_SERVER_TLS
      - TIDEPOOL_CONFIRMATION_STORE_DATABASE
      - TIDEPOOL_TASK_QUEUE_WORKERS
      - TIDEPOOL_TASK_QUEUE_DELAY
      - TIDEPOOL_DEPRECATED_DATA_STORE_DATABASE
      - TIDEPOOL_MESSAGE_STORE_DATABASE
      - TIDEPOOL_PERMISSION_STORE_DATABASE
      - TIDEPOOL_PERMISSION_STORE_SECRET
      - TIDEPOOL_PROFILE_STORE_DATABASE
      - TIDEPOOL_SESSION_STORE_DATABASE
      - TIDEPOOL_SYNC_TASK_STORE_DATABASE
      - TIDEPOOL_USER_STORE_DATABASE
      - TIDEPOOL_USER_STORE_PASSWORD_SALT
      - TIDEPOOL_AUTH_CLIENT_ADDRESS
      - TIDEPOOL_DATA_CLIENT_ADDRESS
      - TIDEPOOL_METRIC_CLIENT_ADDRESS
      - TIDEPOOL_NOTIFICATION_CLIENT_ADDRESS
      - TIDEPOOL_TASK_CLIENT_ADDRESS
      - TIDEPOOL_USER_CLIENT_ADDRESS
      - TIDEPOOL_AUTH_CLIENT_EXTERNAL_ADDRESS
      - TIDEPOOL_AUTH_CLIENT_EXTERNAL_SERVER_SESSION_TOKEN_SECRET
      - TIDEPOOL_AUTH_SERVICE_SERVER_ADDRESS
      - TIDEPOOL_DATA_SERVICE_SERVER_ADDRESS
      - TIDEPOOL_NOTIFICATION_SERVICE_SERVER_ADDRESS
      - TIDEPOOL_TASK_SERVICE_SERVER_ADDRESS
      - TIDEPOOL_USER_SERVICE_SERVER_ADDRESS
      - TIDEPOOL_AUTH_SERVICE_DOMAIN
      - TIDEPOOL_AUTH_SERVICE_SECRET
      - TIDEPOOL_DATA_SERVICE_SECRET
      - TIDEPOOL_NOTIFICATION_SERVICE_SECRET
      - TIDEPOOL_TASK_SERVICE_SECRET
      - TIDEPOOL_USER_SERVICE_SECRET
      - TIDEPOOL_DEXCOM_CLIENT_ADDRESS
      - TIDEPOOL_SERVICE_PROVIDER_DEXCOM_CLIENT_ID
      - TIDEPOOL_SERVICE_PROVIDER_DEXCOM_CLIENT_SECRET
      - TIDEPOOL_SERVICE_PROVIDER_DEXCOM_AUTHORIZE_URL
      - TIDEPOOL_SERVICE_PROVIDER_DEXCOM_TOKEN_URL
      - TIDEPOOL_SERVICE_PROVIDER_DEXCOM_REDIRECT_URL
      - TIDEPOOL_SERVICE_PROVIDER_DEXCOM_SCOPES
      - TIDEPOOL_SERVICE_PROVIDER_DEXCOM_STATE_SALT

  platform-blob:
    image: docker.ci.diabeloop.eu/platform-blob
    # build:
    #   context: ${PLATFORM_BLOB_DIR}
    #   dockerfile: Dockerfile.blob
    #   target: ${PLATFORM_BLOB_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_BLOB_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    #   - /go/src/github.com/tidepool-org/platform/_data
    ports:
      - '${PLATFORM_BLOB_PORT_PREFIX}9225:${PLATFORM_BLOB_PORT_PREFIX}9225'
    environment: *platform-environment

  platform-data:
    image: docker.ci.diabeloop.eu/platform-data
    # build:
    #   context: ${PLATFORM_DATA_DIR}
    #   dockerfile: Dockerfile.data
    #   target: ${PLATFORM_DATA_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_DATA_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    ports:
      - '${PLATFORM_DATA_PORT_PREFIX}9220:${PLATFORM_DATA_PORT_PREFIX}9220'
    environment: *platform-environment

  platform-migrations:
    image: docker.ci.diabeloop.eu/platform-migrations
    # build:
    #   context: ${PLATFORM_MIGRATIONS_DIR}
    #   dockerfile: Dockerfile.migrations
    #   target: ${PLATFORM_MIGRATIONS_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_MIGRATIONS_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    environment: *platform-environment

  platform-notification:
    image: docker.ci.diabeloop.eu/platform-notification
    # build:
    #   context: ${PLATFORM_NOTIFICATION_DIR}
    #   dockerfile: Dockerfile.notification
    #   target: ${PLATFORM_NOTIFICATION_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_NOTIFICATION_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    ports:
      - '${PLATFORM_NOTIFICATION_PORT_PREFIX}9223:${PLATFORM_NOTIFICATION_PORT_PREFIX}9223'
    environment: *platform-environment

  platform-task:
    image: docker.ci.diabeloop.eu/platform-task
    # build:
    #   context: ${PLATFORM_TASK_DIR}
    #   dockerfile: Dockerfile.task
    #   target: ${PLATFORM_TASK_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_TASK_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    ports:
      - '${PLATFORM_TASK_PORT_PREFIX}9224:${PLATFORM_TASK_PORT_PREFIX}9224'
    environment: *platform-environment

  platform-tools:
    image: docker.ci.diabeloop.eu/platform-tools
    # build:
    #   context: ${PLATFORM_TOOLS_DIR}
    #   dockerfile: Dockerfile.tools
    #   target: ${PLATFORM_TOOLS_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_TOOLS_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    environment: *platform-environment

  platform-user:
    image: docker.ci.diabeloop.eu/platform-user
    # build:
    #   context: ${PLATFORM_USER_DIR}
    #   dockerfile: Dockerfile.user
    #   target: ${PLATFORM_USER_BUILD_TARGET}
    # volumes:
    #   - ${PLATFORM_USER_DIR}:/go/src/github.com/tidepool-org/platform:cached
    #   - /go/src/github.com/tidepool-org/platform/_bin
    ports:
      - '${PLATFORM_USER_PORT_PREFIX}9221:${PLATFORM_USER_PORT_PREFIX}9221'
    environment: *platform-environment

  seagull:
    image: docker.ci.diabeloop.eu/seagull
    depends_on:
      - hakken
    # build: ${SEAGULL_DIR}
    # volumes:
    #   - ${SEAGULL_DIR}:/app:cached
    #   - /app/node_modules
    ports:
      - '${SEAGULL_PORT_PREFIX}9120:${SEAGULL_PORT_PREFIX}9120'
    environment:
      - DISCOVERY_HOST
      - GATEKEEPER_SERVICE
      - METRICS_SERVICE
      - MONGO_CONNECTION_STRING=${SEAGULL_MONGO_CONNECTION_STRING}
      - NODE_ENV
      - PORT=${SEAGULL_PORT}
      - PUBLISH_HOST
      - SALT_DEPLOY="${SEAGULL_SALT}"
      - SERVER_SECRET
      - SERVICE_NAME="${SEAGULL_SERVICE_NAME}"
      - USER_API_SERVICE

  shoreline:
    image: docker.ci.diabeloop.eu/shoreline
    depends_on:
      - hakken
    # build:
    #   context: ${SHORELINE_DIR}
    #   target: ${SHORELINE_BUILD_TARGET}
    # volumes:
    #   - ${SHORELINE_DIR}:/go/src/github.com/tidepool-org/shoreline:cached
    #   - /go/src/github.com/tidepool-org/shoreline/dist
    ports:
      - '${SHORELINE_PORT_PREFIX}9107:${SHORELINE_PORT_PREFIX}9107'
    environment:
      - TIDEPOOL_SHORELINE_ENV
      - TIDEPOOL_SHORELINE_SERVICE

  styx:
    image: docker.ci.diabeloop.eu/styx
    depends_on:
      - hakken
    # build: ${STYX_DIR}
    # volumes:
    #   - ${STYX_DIR}:/app:cached
    #   - /app/node_modules
    ports:
      - '${STYX_PORT_PREFIX}8009-${STYX_PORT_PREFIX}8010:${STYX_PORT_PREFIX}8009-${STYX_PORT_PREFIX}8010'
    environment:
      - DISCOVERY
      - HTTPS_CONFIG
      - HTTPS_PORT
      - HTTP_PORT
      - NODE_ENV
      - RULES   

  tide-whisperer:
    image: docker.ci.diabeloop.eu/tide-whisperer
    depends_on:
      - hakken
    # build:
    #   context: ${TIDE_WHISPERER_DIR}
    #   target: ${TIDE_WHISPERER_BUILD_TARGET}
    # volumes:
    #   - ${TIDE_WHISPERER_DIR}:/go/src/github.com/tidepool-org/tide-whisperer:cached
    #   - /go/src/github.com/tidepool-org/tide-whisperer/dist
    ports:
      - '${TIDE_WHISPERER_PORT_PREFIX}9127:${TIDE_WHISPERER_PORT_PREFIX}9127'
    environment:
      - TIDEPOOL_TIDE_WHISPERER_ENV
      - TIDEPOOL_TIDE_WHISPERER_SERVICE

  # viz:
  #   image: tidepool/viz
  #   volumes:
  #     - ${VIZ_DIR}:/app:cached
  #     - /app/node_modules
  #     - viz-dist:/app/dist
  #   environment:
  #     - NODE_ENV
  #   ports:
  #     - '8081:8081'
  #     - '8082:8082'

  confirm-email:
    image: docker.ci.diabeloop.eu/confirm-email
    ports:
      - '9508:9508'
    environment:
      PORT: ${CONFIRM_EMAIL_PORT}
      MONGO_USER_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/user'
      DIABELOOP_SECRET: '${CONFIRM_EMAIL_SECRET}'
      CRYPTOGRAPHY: ${CONFIRM_EMAIL_CRYPTOGRAPHY}
      SERVER: ${CONFIRM_EMAIL_HOST}

  mis-api:
    image: mis-api
    ports:
      - '9510:9510'
    environment:
      MONGO_USER_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/user'
      MONGO_GATEKEEPER_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/gatekeeper'
      MONGO_PORTAL_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/portal'
      MONGO_SEAGULL_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/seagull'
      MONGO_DATA_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/data'
      MONGO_MIS_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/mis'
      TIDEPOOL_API_HOST: 'http://${API_HOST}:8009'
      MDBLP_API_HOST: 'localhost'
      MDBLP_API_PORT: '9510'
      MDBLP_API_LOGLEVEL: 'Info'
      MDBLP_API_LOGFILE: '../mis.log'

  portal-api:
    image: portal-api
    ports:
      - '9507:9507'
    environment:
      MONGO_USER_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/user'
      MONGO_GATEKEEPER_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/gatekeeper'
      MONGO_PORTAL_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/portal'
      MONGO_SEAGULL_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/seagull'
      MONGO_DATA_CONNECTION_STRING: 'mongodb://${MONGO_HOST}/data'
      API_HOST: 'http://localhost:8009'
      GATEKEEPER_SECRET_KEY: '${GATEKEEPER_SECRET}'
      HOST: 'localhost'
      PORT: 9507
      DEFAULT_ADMIN_EMAIL: 'admin@portal.com'
      DEFAULT_ADMIN_PASSWORD: 'password'
      DEFAULT_ADMIN_USERID: 'portal-admin'
      SHORELINE_PASSWORD_SALT: '${SHORELINE_SALT}'

volumes:
  mongo:
