deployment:
  # image: tidepool/message-api:master-latest
  image: docker.ci.diabeloop.eu/message-api
  replicas: 1
  env:
    window: 21
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
nodeEnvironment: production
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
