secret:
  enabled: false
  data_:
    ServiceAuth: ""
deployment:
  # image: tidepool/platform-task:master-latest
  image: docker.ci.diabeloop.eu/mdblp/platform-task
  replicas: 1
  env:
    queue:
      delay: 5
      workers: 5
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
