deployment:
  image: docker.ci.diabeloop.eu/health-check
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
nodeEnvironment: production
pdb:
  enabled: false
  minAvailable: 1

