deployment:
  podAnnotations: {}
  image: docker.ci.diabeloop.eu/portal-front
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
