deployment:
  # image: tidepool/hydrophone:master-latest
  image: docker.ci.diabeloop.eu/hydrophone
  replicas: 1
  env:
    fromAddress: "Tidepool <noreply@tidepool.org>"                      # from address for emails that we send
    store:
      s3:
        bucket: "asset"
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
serviceAccount:
  create: false
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
