deployment:
  podAnnotations: {}
  # image: tidepool/blip:master-latest
  image: docker.ci.diabeloop.eu/blip
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
