secret:
  enabled: false
  data_:
    ServiceAuth: ""
deployment:
  # image: tidepool/platform-notification:master-latest
  image: docker.ci.diabeloop.eu/mdblp/platform-notification
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
