secret:
  enabled: false
  data_:
    ServiceAuth: ""
deployment:
  replicas: 1
  # image: tidepool/platform-blob:master-latest
  image: docker.ci.diabeloop.eu/mdblp/platform-blob
  env:
    store:
      s3:
        bucket: "data"
        prefix: "blobs"
      file:
        prefix: "blobs"
        directory: "_data/blobs"                                            # directory to use if using local file storage
      type: file
      #type: s3
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
serviceAccount:
  create: false
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
