---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blip
{{ include "charts.labels.standard" .}}
  name: blip
  namespace: {{.Release.Namespace}}
  annotations:
{{ if .Values.deployment.annotations }}
    {{- .Values.deployment.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: blip
      app.kubernetes.io/name: {{ include "charts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      labels:
        app: blip
        app.kubernetes.io/name: {{ include "charts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{ if .Values.podAnnotations }}
      annotations:
        {{- .Values.podAnnotations | toYaml | nindent 8 }}
{{- end }}
    spec:
      containers:
      - image: "{{ .Values.deployment.image }}:{{ .Values.global.versions.blip }}"
        securityContext:
          {{- .Values.podSecurityContext | toYaml | nindent 10 }}
{{ if .Values.command }}
        command: {{ .Values.command }}
{{- end }}
{{ if .Values.args }}
        args: {{ .Values.args }}
{{- end }}
        env:
        - name: SKIP_HAKKEN
          value: "true"
        - name: BRANDING
          value: "diabeloop"
        - name: PASSWORD_MIN_LENGTH
          value: "10"
        - name: PASSWORD_MAX_LENGTH
          value: "72"
        - name: HELP_LINK
          value: "https://static.zdassets.com/ekr/snippet.js?key=d2da97fd-9e77-4cf0-8d12-4c7412e40471"
        - name: ASSETS_URL
          value: "https://s3-eu-west-1.amazonaws.com/com.diabeloop.public-assets/"
        - name: I18N_ENABLED
          value: "true"
        - name: ALLOW_SIGNUP_PATIENT
          value: "false"
        - name: ALLOW_PATIENT_CHANGE_EMAIL
          value: "false"
        - name: ALLOW_PATIENT_CHANGE_PASSWORD
          value: "false"
        - name: ALLOW_CHANGE_LANG
          value: "false"
        - name: HIDE_DONATE
          value: "true"
        - name: HIDE_DEXCOM_BANNER
          value: "true"
        - name: HIDE_UPLOAD_LINK
          value: "true"
{{ if .Values.webpackPublicPath }}
        - name: WEBPACK_PUBLIC_PATH
          value: {{ .Values.webpackPublicPath }}
{{- end }}
{{ if .Values.webpackDevTool }}
        - name: WEBPACK_DEVTOOL
          value: {{ .Values.webpackDevTool }}
{{- end }}
{{ if .Values.webpackDevToolViz }}
        - name: WEBPACK_DEVTOOL_VIZ
          value: {{ .Values.webpackDevToolViz }}
{{- end }}
{{ if .Values.disableDevTools }}
        - name: DEV_TOOLS
          value: 'false'
{{ end }}
{{ if .Values.apiHost }}
        - name: API_HOST
          value: {{ .Values.apiHost }}
{{- end }}
        name: blip
        ports:
        - containerPort: {{.Values.global.ports.blip}}
{{ range $key, $port := .Values.global.ports.viz }}
        - containerPort: {{ $port }}
{{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      restartPolicy: Always
      imagePullSecrets:
      - name: nexuscred
