enabled: true
deployment:
  # image: tidepool/platform-migrations:master-latest
  image: docker.ci.diabeloop.eu/mdblp/platform-migrations
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
