---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task
{{ include "charts.labels.standard" .}}
  name: task
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: "http"
    port: {{ .Values.global.ports.task }}
    targetPort: {{ .Values.global.ports.task }}
  selector:
    app: task
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
