configmap:
  enabled: false
  data:
    ClinicDemoUserId: ""
secret:
  enabled: false
  data_:
    ServiceAuth: ""
    UserLongTermKey:
    UserMailVerification: ""
    ClinicDemoUserId: ""
deployment:
  # image: tidepool/shoreline:master-latest
  image: docker.ci.diabeloop.eu/shoreline
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
