global:
  maxTimeout: 120s
  fullnameOverride: ""                             #
  nameOverride: ""                                 # the name to use for the helm chart, if given
  region: "us-west-2"                              # AWS region
  logLevel: info                                   # the default log level for all services
  gateway:
    default:
      protocol: http
      host: localhost
    proxy:
      name: gateway-proxy
      namespace: gloo-system
  ports:
    blip: 3000                                     # blip service internal port
    export: 9300                                   # export service internal port
    gatekeeper: 9123                               # gatekeeper service internal port
    highwater: 9191                                # highwater service internal port
    hydrophone: 9157                               # hydrophone service internal port
    jellyfish: 9122                                # jellyfish service internal port
    messageapi: 9119                               # messageapi service internal port
    auth: 9222                                     # auth service internal port
    blob: 9225                                     # blob service internal port
    data: 9220                                     # data service internal port
    image: 9226                                    # image service internal port
    notification: 9223                             # notification service internal port
    task: 9224                                     # task service internal port
    user: 9221                                     # user service internal port
    seagull: 9120                                  # seagull service internal port
    shoreline: 9107                                # shoreline service internal port
    tidewhisperer: 9127                            # tidewhisperer service in 
  versions:
    blip: "0.14.1"
    export: "1.4.2"
    gatekeeper: "0.2.2"
    highwater: "0.1.4"
    hydrophone: "0.8.0"
    messageapi: "0.2.0"
    platform: "0.7.1"
    seagull : "0.3.2"
    shoreline: "0.5.2"
    tidewhisperer: "0.5.2"
  secret:
    enabled: false
    generated: false
    templated: false
glooingress:
  enabled: true
linkerdsupport:
  enabled: false
tidepool:
  namespace:
    create: true
    annotations: {}                                # namespace annotations
