secret:
  enabled: false
  data_:
    ServiceAuth: ""
    AppleDeviceCheckKey: ""
configmap:
  data_:
    AppleDeviceCheckKeyIssuer: "75U4X84TEG"
    AppleDeviceCheckKeyId: "B542R658GF"
    AppleDeviceCheckUseDevelopment: "true"
deployment:
  # image: tidepool/platform-auth:master-latest
  image: docker.ci.diabeloop.eu/mdblp/platform-auth
  replicas: 1
resources: {}
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
hpa:
  enabled: false
pdb:
  enabled: false
  minAvailable: 1
mongo:
  secretName: mongo
