{{- $spec := .Values.virtualServices.https }}
{{ if $spec.enabled }}
{{- $port := $spec.port | default "443" }}
{{- $hsts := $spec.hsts | default true }}
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: {{ $spec.name }}
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- range $key, $value := $spec.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  displayName: https
  sslConfig:
    secretRef:
      name: {{ $spec.certificateSecretName | default "https-certificate" | quote }}
      namespace: '{{ $.Release.Namespace }}'
    sniDomains:
{{- range $dnsName := $spec.dnsNames }}
    - '{{ $dnsName }}'
{{- end }}
  virtualHost:
    domains:
{{- range $dnsName := $spec.dnsNames }}
    - '{{ if ne $port "443" -}}{{- printf "%s:%s" $dnsName $port -}} {{- else -}} {{ printf "%s" $dnsName -}}{{- end -}}'
{{- end  }}
    options:
      stats:
{{- if $spec.options.stats }}
{{- toYaml $spec.options.stats | nindent 8 }}
{{- end }}
      cors:
        allowCredentials: true
        allowHeaders:
        - authorization
        - content-type
        - x-tidepool-session-token
        - x-tidepool-trace-request
        - x-tidepool-trace-session
        allowMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
        allowOriginRegex:
        - .*
        exposeHeaders:
        - x-tidepool-session-token
        - x-tidepool-trace-request
        - x-tidepool-trace-session
        maxAge: 600s
{{- if $hsts }}
      headerManipulation:
        requestHeadersToAdd:
        - header:
            key: Strict-Transport-Security
            value: max-age=31536000
{{- end }}
    routes:
    - matchers:
      - prefix: '/'
      delegateAction:
        name: {{ .Values.routeTable.name }}
        namespace: {{ .Release.Namespace }}
{{- end }}
